### ISSUE TITLE
micro note

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_tab_rename#4]
1.
```
      pre = j.get(PREFIX_KEY)
      if pre != None:
        prefix = pre
```
equals to
prefix = j.get(PREFIX_KEY, prefix)
?

2. why not

```
[item1]
section=events
events=on_open,on_save
```

**Comment by Alexey-T** [comment]
events=on_open,on_save

without space (fixed prev msg).

**Comment by halfbrained** [comment]
1 - A brainfart  (fixed)
2 - I could never remember if it is coma or semicolon :) (fixed)

**Comment by Alexey-T** [comment]
it is comma.

**Comment by Alexey-T** [comment]
@halfbrained do you need the donation for your work? I can send 20..50$ if you need the donation.

**Comment by halfbrained** [comment]
No need. It is a thanks for an amazing program :)
