### ISSUE TITLE
rename also related .cuda-pic

### ISSUE THREAD

**Issue by MiroslavMatas** [halfbrained/cuda_tab_rename#7]
if renamed file have also "sister" file for pictures… than resulting situation is not so well - and I must to rename .cuda-pic manually

will be possible to update this plugin?

**Comment by Alexey-T** [comment]
Installed Tab-Rename, now I cannot see where it renames the file. it renames only tab-title of file! while file name is old.

**Comment by Alexey-T** [comment]
Maybe you talk about CudaExt's "Rename file"?

**Comment by Alexey-T** [comment]
I patched CudaExt.
See my fork in
https://github.com/Alexey-T/cuda_ext/tree/patch-1
in the branch 'patch-1'

**Comment by MiroslavMatas** [comment]
> Installed Tab-Rename, now I cannot see where it renames the file. it renames only tab-title of file! while file name is old.

feel like idiot… you are true, of course

**Comment by MiroslavMatas** [comment]
> I patched CudaExt. See my fork in https://github.com/Alexey-T/cuda_ext/tree/patch-1 in the branch 'patch-1'

brilliant, works fine and as expected
